USE EtlNetflix;

ALTER TABLE [ClassificacaoEtaria]
ADD CodExterno NVARCHAR(12);

ALTER TABLE Serie  
DROP CONSTRAINT [FK_Serie_IdDiretor];   
ALTER TABLE Diretor  
DROP CONSTRAINT PK_DIRETOR;  
ALTER TABLE Diretor ADD PRIMARY KEY (IdDiretor)

ALTER TABLE Serie  
DROP CONSTRAINT [FK_Serie_IdProdutora];    
ALTER TABLE Produtora  
DROP CONSTRAINT PK_PRODUTORA;   
ALTER TABLE Produtora ADD PRIMARY KEY (IdProdutora)

ALTER TABLE Serie  
DROP CONSTRAINT [FK_Serie_IdPaisOrigem];    
ALTER TABLE PaisOrigem  
DROP CONSTRAINT [PK_PAISORIGEM];   
ALTER TABLE PaisOrigem ADD PRIMARY KEY (IdPais)

ALTER TABLE Serie  
DROP CONSTRAINT [FK_Serie_IdClassificacaoEtaria];    
ALTER TABLE ClassificacaoEtaria  
DROP CONSTRAINT [PK_CLASSIFICACAOETARIA];   
ALTER TABLE ClassificacaoEtaria ADD PRIMARY KEY (IdClassificacaoEtaria)

ALTER TABLE Serie
DROP COLUMN [IdDiretor];
ALTER TABLE Serie
DROP COLUMN [IdProdutora];
ALTER TABLE Serie
DROP COLUMN [IdPaisOrigem];
ALTER TABLE Serie
DROP COLUMN IdClassificacaoEtaria;
ALTER TABLE Serie
ADD Url NVARCHAR(400) NOT NULL;
ALTER TABLE Serie
ADD Genero NVARCHAR(100) NOT NULL;
ALTER TABLE Serie
ADD ClassificacaoEtaria NVARCHAR(20) NOT NULL;
ALTER TABLE Serie
ADD Temporada NVARCHAR(100) NOT NULL;
